<a href="https://colab.research.google.com/github/masolopa/MINERIADEDATOS/blob/main/EV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

#El contexto del data set es sobre las estimaciones de taza de pobreza multidimensional por comuna en Chile del año 2015
#Integrantes: Alejandra Guzman - Macarena Lobos
#https://github.com/masolopa/MINERIADEDATOS

In [2]:
#Se importa el data set del año 2015
df = pd.read_excel("/content/planilla_estimaciones_pobreza_2015.xlsx")

In [3]:
#Se observa el data frame en bruto
df

,"Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Código,Región,Nombre comuna,Número de personas en situación de pobreza por...,Porcentaje de personas en situación de pobreza...,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
...,...,...,...,...,...,...,...,...
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [4]:
#Se eliminan las primeras dos filas del data frame seleccionando el número de posición de cada fila a la vez
df = df.drop(index= [0, 1])

In [5]:
#Se observa el data frame con las dos filas de posición 0 y 1 eliminadas
df

,"Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC
...,...,...,...,...,...,...,...,...
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [6]:
#Se consultan los nombres de las columnas del data frame
print("Nombres de columnas actuales:")
print(df.columns.tolist())

Nombres de columnas actuales:
['Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

In [7]:
#Se renombran las columnas
df.columns = ['Código comuna', 'Región','Nombre comuna', 'Número de personas en situación de pobreza por ingresos','Porcentaje de personas en situación de pobreza por ingresos', 'Límite inferior','Límite superior', 'Metodología de Estimación']
display(df.head())

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC

In [8]:
#df.to_csv("modificado.csv") Se hace una conversión del data frame a versión csv, ya que la base de origen es tipo excel

In [9]:
#Se muestran las primeras 5 filas
df.head()

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC

In [10]:
#Se muestran las últimas 5 filas del data frame
df.tail()

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [11]:
#Se listan las columnas del data frame
df.columns

Index(['Código comuna', 'Región', 'Nombre comuna',
       'Número de personas en situación de pobreza por ingresos',
       'Porcentaje de personas en situación de pobreza por ingresos',
       'Límite inferior', 'Límite superior', 'Metodología de Estimación'],
      dtype='object')

In [12]:
#Se revisan los valores nulos de cada columna del data fram
df.isna().sum()

Código comuna                                                   0
Región                                                          0
Nombre comuna                                                   0
Número de personas en situación de pobreza por ingresos         0
Porcentaje de personas en situación de pobreza por ingresos     0
Límite inferior                                                21
Límite superior                                                21
Metodología de Estimación                                       0
dtype: int64

In [13]:
#Se importa el data set del año 2024
df2 = pd.read_excel("/content/sae_multidimensional_2024.xlsx")

In [14]:
df2

,Estimaciones de Índice de Pobreza Multidimensional por comuna. Aplicación de Metodologías de Estimación para Áreas Pequeñas (SAE) 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Código,Región,Nombre comuna,Número de personas según proyecciones de pobla...,Número de personas en situación de pobreza mul...,Porcentaje de personas en situacion de pobreza...,Límite inferior,Límite superior,Presencia de la comuna en la muestra Casen,Tipo de estimación SAE (***)
2,1101,Tarapacá,Iquique,232455,43108.781225,0.18545,0.163506,0.207394,Sí,Directa y Sintética (Fay-Herriot)
3,1107,Tarapacá,Alto Hospicio,144554,40866.517698,0.282708,0.255357,0.310058,Sí,Directa y Sintética (Fay-Herriot)
4,1401,Tarapacá,Pozo Almonte,18811,3646.420183,0.193845,0.142099,0.245592,Sí,Directa y Sintética (Fay-Herriot)
...,...,...,...,...,...,...,...,...,...,...
348,La metodología de áreas pequeñas busca realiza...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,Las estimaciones presentadas se basan en la nu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,(*) Proyecciones de población comunal en vivie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,(**) Este número se obtiene de multiplicar las...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,(***) Las estimaciones para área pequeña asign...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#Se eliminan las primeras dos filas del data frame 2 seleccionando el número de posición de cada fila a la vez
df2 = df2.drop(index= [0, 1])

In [18]:
#Se renombran las columnas
df.columns = ['Código comuna', 'Región','Nombre comuna', 'Número de personas en situación de pobreza por ingresos','Porcentaje de personas en situación de pobreza por ingresos', 'Límite inferior','Límite superior', 'Metodología de Estimación']
display(df.head())

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
2,1101,I de Tarapacá,Iquique,9491,0.053294,0.034605,0.081227,Estimación Directa
3,1107,I de Tarapacá,Alto Hospicio,9768,0.085072,0.064137,0.112023,Estimación Directa
4,1401,I de Tarapacá,Pozo Almonte,1515,0.103265,0.072762,0.144562,Estimación Directa
5,1402,I de Tarapacá,Camiña,300.2006,0.348665,0.276406,0.453704,SAE
6,1403,I de Tarapacá,Colchane,328.2058,0.239566,NaN,NaN,IMC

In [19]:
#Se muestran las últimas 5 filas del data frame 2
df.tail()

,Código comuna,Región,Nombre comuna,Número de personas en situación de pobreza por ingresos,Porcentaje de personas en situación de pobreza por ingresos,Límite inferior,Límite superior,Metodología de Estimación
342,14204,XIV de los Ríos,Rio Bueno,5113,0.171232,0.107617,0.261436,Estimación Directa
343,15101,XV de Arica y Parinacota,Arica,14573,0.088609,0.068152,0.114452,Estimación Directa
344,15102,XV de Arica y Parinacota,Camarones,217.5172,0.146674,0.07265,0.241199,SAE
345,15201,XV de Arica y Parinacota,Putre,240,0.311284,0.2193,0.421043,Estimación Directa
346,15202,XV de Arica y Parinacota,General Lagos,267.9631,0.277395,NaN,NaN,IMC

In [20]:
df.info() #Muestra en detalle cuantas columnas hay, sus nombres, también muestra que hay 345 filas de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 2 to 346
Data columns (total 8 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Código comuna                                                345 non-null    object
 1   Región                                                       345 non-null    object
 2   Nombre comuna                                                345 non-null    object
 3   Número de personas en situación de pobreza por ingresos      345 non-null    object
 4   Porcentaje de personas en situación de pobreza por ingresos  345 non-null    object
 5   Límite inferior                                              324 non-null    object
 6   Límite superior                                              324 non-null    object
 7   Metodología de Estimación                                    345 non-null    object
dtypes: object(8)
memory usage: 21.7+ KB

In [21]:
df2.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 2 to 352
Data columns (total 10 columns):
 #   Column                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                  --------------  -----
 0   Estimaciones de Índice de Pobreza Multidimensional por comuna. Aplicación de Metodologías de Estimación para Áreas Pequeñas (SAE) 2024  350 non-null    object
 1   Unnamed: 1                                                                                                                              345 non-null    object
 2   Unnamed: 2                                                                                                                              345 non-null    object
 3   Unnamed: 3                                                                                                                              345 non-null    object
 4   Unnamed: 4                                                                                                                              345 non-null    object
 5   Unnamed: 5                                                                                                                              345 non-null    object
 6   Unnamed: 6                                                                                                                              345 non-null    object
 7   Unnamed: 7                                                                                                                              345 non-null    object
 8   Unnamed: 8                                                                                                                              345 non-null    object
 9   Unnamed: 9                                                                                                                              345 non-null    object
dtypes: object(10)
memory usage: 27.6+ KB