<a href="https://colab.research.google.com/github/masolopa/MINERIADEDATOS/blob/main/EV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

#El contexto del data set es de el flujo aéreo de Chile

In [26]:
df = pd.read_excel("/content/planilla_estimaciones_comunales_tasa_pobreza_por_ingresos_multidimensional_2015.xlsx")

In [27]:
df

    Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015  ...                 Unnamed: 7
0                                                  NaN                                                                                                                                                                                        ...                        NaN
1                                               Código                                                                                                                                                                                        ...  Metodología de Estimación
2                                                 1101                                                                                                                                                                                        ...         Estimación Directa
3                                                 1107                                                                                                                                                                                        ...         Estimación Directa
4                                                 1401                                                                                                                                                                                        ...         Estimación Directa
..                                                 ...                                                                                                                                                                                        ...                        ...
342                                              14204                                                                                                                                                                                        ...         Estimación Directa
343                                              15101                                                                                                                                                                                        ...         Estimación Directa
344                                              15102                                                                                                                                                                                        ...                        SAE
345                                              15201                                                                                                                                                                                        ...         Estimación Directa
346                                              15202                                                                                                                                                                                        ...                        IMC

[347 rows x 8 columns]

In [29]:
df = df.drop(index= [0, 1])

In [31]:
df

    Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015  ...          Unnamed: 7
2                                                 1101                                                                                                                                                                                        ...  Estimación Directa
3                                                 1107                                                                                                                                                                                        ...  Estimación Directa
4                                                 1401                                                                                                                                                                                        ...  Estimación Directa
5                                                 1402                                                                                                                                                                                        ...                 SAE
6                                                 1403                                                                                                                                                                                        ...                 IMC
..                                                 ...                                                                                                                                                                                        ...                 ...
342                                              14204                                                                                                                                                                                        ...  Estimación Directa
343                                              15101                                                                                                                                                                                        ...  Estimación Directa
344                                              15102                                                                                                                                                                                        ...                 SAE
345                                              15201                                                                                                                                                                                        ...  Estimación Directa
346                                              15202                                                                                                                                                                                        ...                 IMC

[345 rows x 8 columns]

### Renombrar columnas del DataFrame

Hay dos maneras principales de renombrar columnas:

1.  **Usando el método `df.rename()` con un diccionario**: Esta es la forma recomendada cuando quieres cambiar solo algunas columnas.
2.  **Asignando una nueva lista a `df.columns`**: Útil cuando quieres renombrar todas las columnas a la vez, asegurándote de que la lista tenga el mismo número de elementos que las columnas actuales y en el orden correcto.

In [ ]:
# Para ver los nombres de las columnas actuales:
print("Nombres de columnas actuales:")
print(df.columns.tolist())

# Renombrar columnas específicas usando un diccionario
# Se reemplazará el nombre original por el nuevo nombre
new_column_names = {
    'Estimaciones de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación de Medias por Conglomerados (IMC), 2015': 'Codigo Comuna',
    'Unnamed: 7': 'Metodologia Estimacion'
}

df = df.rename(columns=new_column_names)

# Mostrar los primeros 5 registros con las columnas renombradas para verificar
display(df.head())

Si quisieras renombrar todas las columnas, podrías hacer lo siguiente (asegúrate de que la nueva lista tenga la misma longitud que el número de columnas actual):

```python
# Ejemplo de cómo renombrar todas las columnas (DESCOMENTA Y EJECUTA SI ES NECESARIO)
# df.columns = ['Nueva_Columna_1', 'Nueva_Columna_2', ..., 'Nueva_Columna_N']
# display(df.head())
```

In [28]:
# Method 1: Eliminar una fila por su índice (si conoces el índice de la fila)
# Por ejemplo, para eliminar la fila con índice 0 (la primera fila):
df = df.drop(index=0)

# Si quieres eliminar múltiples filas por sus índices:
# df = df.drop(index=[0, 2, 5])

# Para hacer el cambio directamente en el DataFrame original sin reasignar:
# df.drop(index=0, inplace=True)


# Method 2: Eliminar filas basándose en una condición de una columna

# Por ejemplo, si quieres eliminar todas las filas donde la columna 'Estimaciones
# de Tasa de Pobreza Multidimensional por Comuna, considerando Entorno y Redes y Aplicación
#de Metodologías de: Estimación directa, Estimación para Áreas Pequeñas (SAE) e Imputación
#de Medias por Conglomerados (IMC), 2015' tenga un valor específico (asumiendo que es el
#nombre de la primera columna que se mostró en df, probablemente necesites ajustarlo).
# Supongamos que quieres eliminar filas donde la primera columna (el nombre largo) es
#'ValorEspecificoARemover'

# Primero, obtén el nombre exacto de la primera columna (ajusta si es necesario)
first_column_name = df.columns[0]

# Ejemplo: Eliminar filas donde la primera columna tiene el valor 'Estimación Directa'
#(esto es solo un ejemplo, ajusta el valor según lo que necesites eliminar)
# df = df[df[first_column_name] != 'Estimación Directa']

# Ejemplo: Eliminar filas donde una columna numérica 'NombreColumnaNumerica' es mayor que 100
# df = df[df['NombreColumnaNumerica'] <= 100]


# Después de ejecutar el método que elijas, puedes verificar el DataFrame actualizado
df.head()